import { Open_Sans } from "next/font/google";
import "./globals.css";

const Open_Sanss= Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Google Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Open_Sanss.className}>{children}</body>
    </html>
  );
}
